### ISSUE TITLE
NaN caught when computing momentary loudness over negative zeros

### ISSUE THREAD

**Issue by kakyoism** [kfrlib/kfr#100]
I got a problem where if the buffer fed to `ebu128`'s packet contains all negative zeros, the momentary loudness will be `nan`.  

Is this by design? Does kfr accept negative zeros as input data at all?

**Comment by samuelriddle** [comment]
Could you give more details about your compiler and target cpu architecture/compiler flags?

**Comment by kakyoism** [comment]
Target platform: iOS (arm64)
Xcode 11.6
Compiler: Apple clang version 11.0.3 (clang-1103.0.32.62)

CMake command

```sh
cmake -GXcode \
        -DENABLE_TESTS=ON \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_TOOLCHAIN_FILE="$ProjDir"/cmake/ios.cmake \
        -DIOS_PLATFORM=OS64 \
       "$ProjDir"
```

Then

```sh
    xcodebuild -project kfr.xcodeproj \
        -scheme kfr_dft \
        -configuration Release \
        -destination "platform=iOS,name=$DEVICE" \
        build
```

No custom compiler tweaks on the generated Xcode project.

**Comment by dancazarin** [comment]
Closed due to inactivity. Feel free to reopen if the problem still exists.
