### ISSUE TITLE
carg error?

### ISSUE THREAD

**Issue by mipac** [kfrlib/kfr#107]
I have kfr::carg(kfr::complex<float>(1,0)) == pi/2 and kfr::carg(kfr::complex<float>(0,1)) == 0

in the code there is :
return atan2(even(xx), odd(xx));
but shouldn't it be 
return atan2(odd(xx), even(xx));

ie atan2(imag, real)

regards

**Comment by samuelriddle** [comment]
Thank you for reporting. It will be fixed in the next patch release.

**Comment by dlevin256** [comment]
Hi,

The issue has been fixed in master branch.
