### ISSUE TITLE
expression as class member

### ISSUE THREAD

**Issue by mipac** [kfrlib/kfr#108]
Is it possible to define a class member as a kfr::gen_sin for example?
Or how can I use a generator in class methods?

**Comment by samuelriddle** [comment]
Hi,
`expression_pointer<T>` has been created exactly for this purpose. Use `to_pointer<T>` function to convert an expression (or a generator which is expression too) to pointer.
`T` means the type of generated values.
Note that `expression_pointer` has shared-pointer semantics (like `std::shared_ptr`).

Example:
```c++
class MyClass
{
    template <typename ExprTpl>
    MyClass(ExprTpl&& expr_tpl): expr( to_pointer<float>( std::forward<ExprTpl>(expr_tpl) ) ) {}
    void process(float* data, size_t size)
    {
        make_univector(data, size) = expr * 0.5f;
    }
    expression_pointer<float> expr;
};
```

**Comment by mipac** [comment]
perfect! thank you very much
