### ISSUE TITLE
How to use KFR in Xcode?

### ISSUE THREAD

**Issue by iooops** [kfrlib/kfr#11]
I wonder how I can use KFR as a framework in my Xcode Project.

Does anyone have any idea?

Thanks.

**Comment by dlevin256** [comment]
KFR is a header-only, no need to compile anything to use it in your project.
Easiest way to use KFR is to place kfr headers in a location that are in your `#include` paths or place in the project folder.
KFR has no specific requirements, just use it as any other header-only library.
