### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by asesidaa** [kfrlib/kfr#117]
I tried several methods, but every time I get a link error

`lld-link: error: undefined symbol: struct kfr::univector<signed char, 4294967295> __cdecl kfr::sse2::intrinsics::convolve<signed char>(struct kfr::univector<signed char const, 0> const &, struct kfr::univector<signed char const, 0> const &)`

I am working on windows 10. What might be the problem?

**Comment by dlevin256** [comment]
You need to link against kfr_dft to use convolution.
