### ISSUE TITLE
fft_accuracy test failure with Clang 11

### ISSUE THREAD

**Issue by m-hagelin** [kfrlib/kfr#119]
The testcase fft_accuracy fails quite badly after building with clang 11.

```
...
    type = float, size = 254; complex-inverse:
    [fail]    rms_diff_outofplace < min_prec | 6.27181 < 0.00140648
[----RUN----] dct...
[--SUCCESS--] 2 subtests of 2
===============================================================================
[--SUCCESS--] 145/146 tests 2677857/2678067 checks
[---ERROR---] 1/146 tests 210/2678067 checks
              fft_accuracy
```
* My development machine is running Fedora 33, and I build with clang-11, cmake 3.18.4 and Ninja, the cpu is an i7-10510U, and the build uses avx2.
* It worked with clang-10, and interestingly enough I have seen no issues when building in debug either.
* Also get a lot of psABI warnings, but don't think the ABI would pertain to this issue seeing how the tests are all in the same application built with the same toolchain.

**Comment by slarew** [comment]
I see the same failures in the fft_accuracy test. I am running archlinux which moved to clang 11 not long ago.  avx2 on an i7 8700k.

**Comment by dlevin256** [comment]
Investigating this. Likely vector optimizer bug in clang 11.
Once a workaround will be found for this, patch for kfr will be released.

**Comment by fcapozzi** [comment]
I found same problem ... any news so far for kfr patch availability ?

**Comment by slarew** [comment]
> I see the same failures in the fft_accuracy test. I am running archlinux which moved to clang 11 not long ago. avx2 on an i7 8700k.

Upgrading to clang 11.0.1 appears to have resolved the failure in the fft_accuracy test.

**Comment by dlevin256** [comment]
Fixed in dev branch with no performance loss (spoiler: `-ffp-contract=fast`).
There was indeed a Clang bug in the code of optimizations enabled by `-ffast-math` switch but fortunately not `-ffp-contract=fast`. Newest Xcode 13 was also affected but clang-cl was not.
