### ISSUE TITLE
How to apply dft to 2d matrix?

### ISSUE THREAD

**Issue by vdgs** [kfrlib/kfr#127]

**Comment by dlevin256** [comment]
At this moment only 1d operations are implemented, mainly because KFR is audio-centered library.

But 2d FFT can be performed with 1d FFT and reordering.

**Comment by dlevin256** [comment]
Upcoming KFR 5.x will include multidimensional array support and 2D FFT.

**Comment by dancazarin** [comment]
All KFR6 features are now in `main` branch
