### ISSUE TITLE
Possible bug in nearest_real_or_complex

### ISSUE THREAD

**Issue by shurtlifkeysight** [kfrlib/kfr#137]
I've been having a pesky vector out of range error pop up in my program when running the to_sos function from iir_design.hpp. I think I've traced one of these errors to line 938. Here there's a for loop that's running over the size of the input list but the vector it is indexing it with (filtered) is always going to be <= the size of the input list, which could cause indexing past the end of the vector.

**Comment by dancazarin** [comment]
Fixed in `dev` branch. Will be moved to `main` once full tests complete.
