### ISSUE TITLE
How to build capi?

### ISSUE THREAD

**Issue by balping** [kfrlib/kfr#142]
I'm following the docs and when I run

```
cmake  -DENABLE_CAPI_BUILD=ON -DCMAKE_BUILD_TYPE=Release ..
```

I get 

```
CMake Error at CMakeLists.txt:243 (install):
  install TARGETS given target "kfr_capi" which does not exist.
```

How can I build `kfr_capi` then?

**Comment by dlevin256** [comment]
What compiler do you use? KFR requires Clang to build C API. What is the version of KFR?

**Comment by balping** [comment]
I was trying gcc. Version is 4.2.1

**Comment by dlevin256** [comment]
Clang is required for C API to provide the best performance.
