### ISSUE TITLE
how do I convert kfr::univector<float> and kfr::univector2d<float> to std::vector<float> and std::vector<std::vector<float>>??

### ISSUE THREAD

**Issue by suziW** [kfrlib/kfr#143]
I am using kfr as an extern library, and need to expose my interface using std::vector to avoid integrate kfr in my package. How should I do the convertion?

**Comment by gopher2008** [comment]
univector does not use std::allocator by default, so you can not simply assign it to std::vector. However, you can get a univector from std::vector via make_univector. 
You may use std::allocator by defining KFR_USE_STD_ALLOCATION according to sources.

**Comment by gicu8ab2** [comment]
Pardon my ignorance, as I'm still a C++ novice.  I have my own application that uses libraries that only work with std::vector, but I'd like to use KFR to do some of my DSP functions.  Is there not a way to convert from std::univector back to std::vector?  Also, the make_univector function appears to want double* as input and not std::vector, so can make_univector just take in a variable directly say of type std::vector<std:float>?

**Comment by gopher2008** [comment]
> Pardon my ignorance, as I'm still a C++ novice. I have my own application that uses libraries that only work with std::vector, but I'd like to use KFR to do some of my DSP functions. Is there not a way to convert from std::univector back to std::vector? Also, the make_univector function appears to want double* as input and not std::vector, so can make_univector just take in a variable directly say of type std::vectorstd:float?

Please read the docs at https://www.kfrlib.com/newdocs/types/

**Comment by DeepSeaMechanic** [comment]
univector is a std::vector sort of. 

std::vector<float> vector;
kfr::univector<float> uni;

std::copy(vector.begin(),vector,end(),uni.begin())

univector2D is just a vector of vectors

**Comment by dancazarin** [comment]
Closed due to inactivity. Feel free to reopen if the problem still exists.
