### ISSUE TITLE
ImportError: No module named scipy

### ISSUE THREAD

**Issue by dfy888** [kfrlib/kfr#144]
this is my example  
CMakeLists.txt :

`
cmake_minimum_required(VERSION 3.15)

SET(CMAKE_CXX_STANDARD 17)

file(MAKE_DIRECTORY ${PROJECT_BINARY_DIR}/svg)

add_executable(main iir.cpp)

set(Python3_ROOT_DIR "/home/jiang/miniconda3/envs/py3_tf2_torch")
find_package(Python3 COMPONENTS Interpreter Development REQUIRED)
find_package(Python3 COMPONENTS NumPy)

include_directories(${Python3_INCLUDE_DIRS})
target_link_libraries(main ${Python3_LIBRARIES})

`

**Comment by dfy888** [comment]
i always solve it!

**Comment by dlevin256** [comment]
The following modules are required by KFR tests and examples:
```
matplotlib scipy numpy
```
You should install it using pip prior to running examples.
