### ISSUE TITLE
g++ 7.1.1 and vec: requested alignment is not an integer constant

### ISSUE THREAD

**Issue by jpcima** [kfrlib/kfr#16]
Hi. I have a compilation error in the master branch of kfr.

On an attempt to use the DFT with Linux and gcc 7.1.1, the following error is produced:

    thirdparty/kfr/include/kfr/base/simd_intrin.hpp: In instantiation of ‘struct kfr::vec<float, 4>’:
    thirdparty/kfr/include/kfr/base/simd_x86.hpp:11:44:   required from here
    thirdparty/kfr/include/kfr/base/simd_intrin.hpp:136:97: error: requested alignment is not an integer constant
     struct alignas(const_min(platform<>::maximum_vector_alignment, sizeof(T) * next_poweroftwo(N))) vec

[origin of the error](https://github.com/kfrlib/kfr/blob/6a15c1b1301177fb844389b2c9d0091d28235926/include/kfr/base/simd_intrin.hpp#L136)

From what I observe, recent gcc refuses to accept the parameter of alignas as a compile time constant.
On the same machine I have also tested with clang and gcc5 and it builds with these other compilers.

**Comment by jpcima** [comment]
After searching it became clear to me what the error really is.

It's the return type of the const_min/const_max functions in [cometa.hpp](https://github.com/kfrlib/kfr/blob/master/include/kfr/cometa.hpp).

    template <typename T>
    constexpr const T& const_min(const T& x, const T& y)

Making it T is a quick but non-general workaround to the problem.

    template <typename T>
    constexpr T const_min(const T& x, const T& y)

A general but more verbose solution could be to return a naked type when parameters are integers, like this.

    template <typename T>
    constexpr typename std::conditional<std::is_integral<T>::value, T, const T &>::type
    const_min(const T& x, const T& y)

**Comment by dlevin256** [comment]
Hi.
Thank you for reporting the issue.
Changes required to support gcc 7 will be added to the repository.

**Comment by foxcob** [comment]
Issue exists with GCC 6.3 as well.  This is the default version of GCC available in Ubuntu 17.04.

**Comment by jdosher** [comment]
Well, it's two months later and I'm encountering this issue with gcc 6.3.0-18 on Debian 9 and the most recent kfr on github. Is there a work-around or a solution? I've only just started trying to use kfr and this doesn't bode well.

**Comment by aklofas** [comment]
I've had lots of issues with GCC (5,6,7) compiler flags. Looks like developers only test against clang, so that might be your only option to compile/develop.

**Comment by skadge** [comment]
Same issue here on Raspbian stretch (gcc 6.3). Workaround suggested by @jpcima works for me (well, until I hit another issue...).

**Comment by mlang** [comment]
A year later, and this bug still exists.  Actually wanted to adopt KFR in a project of mine recently, but failing to build on latest GCC was a show stopper.

**Comment by dlevin256** [comment]
Fixed, works in GCC 8.x

**Comment by acxz** [comment]
I am trying to compile the latest master branch on GCC 9.1 and I am also getting this error.
