### ISSUE TITLE
MSVC build error

### ISSUE THREAD

**Issue by MatthieuMv** [kfrlib/kfr#170]
When building for MSVC 2022 version 5.0.1, the inclusion of one these headers break a static assert:
```
#include <kfr/io/audiofile.hpp>
#include <kfr/io/file.hpp>
```

In function ```ctype_name()``` from ```ctti.hpp```:
```static_assert(length > 0, "");```

Thank you

**Comment by dancazarin** [comment]
Hello @MatthieuMv ,
I couldn't reproduce this in the latest MSVC 2022 with default settings.
To reproduce and fix this issue more information is needed. Please answer the following questions to be able to proceed.
What is the exact version of MSVC 2022? (`cl /version` command in Visual Studio command prompt will print the exact version)
Do you use cmake project or Visual Studio solution?
Have you set c++17 standard (or later)?
Is this static assertion the only error that occurs when including the files you mentioned?
Does it occur with a new project with default settings?

**Comment by dancazarin** [comment]
Closed due to inactivity. Feel free to reopen if the problem still exists.
