### ISSUE TITLE
is_infinite issue with Clang

### ISSUE THREAD

**Issue by xKZL** [kfrlib/kfr#181]
Hello @dancazarin ,

I try to embed KFR library in a program and I am facing some issues with the new definition for "is_infinity", here:
https://github.com/kfrlib/kfr/blob/4e2e8253b304381ed95ea70cd2d73742be40bb67/include/kfr/base/expression.hpp#L197

It seems to be related to this issue:
https://stackoverflow.com/questions/44995196/static-member-access-in-constant-expressions

Any possible fix or alternative idea ?

**Comment by dancazarin** [comment]
Closed due to inactivity. Feel free to reopen if the problem still exists.

**Comment by xkzl** [comment]
Hello @dancazarin 

Just got some dedicated time to try to tackle this issue I was facing.
I just updated to KFR 5.1 and here are the precise error messages:

```
kfr/5.1.0/include/kfr/base/expression.hpp:197:23: error: constexpr variable 'is_infinite<kfr::expression_concatenate<kfr::univector<kfr::complex<double>, 18446744073709551615> &, kfr::expression_function<kfr::fn::cconj, kfr::univector<kfr::complex<double>, 18446744073709551615> &>, 0>>' must be initialized by a constant expression
constexpr inline bool is_infinite = expression_traits<E>::get_shape().has_infinity();

kfr/5.1.0/include/kfr/base/univector.hpp:410:24: note: in instantiation of variable template specialization 'kfr::is_infinite<kfr::expression_concatenate<kfr::univector<kfr::complex<double>, 18446744073709551615> &, kfr::expression_function<kfr::fn::cconj, kfr::univector<kfr::complex<double>, 18446744073709551615> &>, 0>>' requested here
        static_assert(!is_infinite<Input>, "Dynamically sized vector requires finite input expression");
                       ^
```

I think this is basically not related to my code.
I am just trying to link a dummy empty skeleton code with the KFR library.

**Comment by dancazarin** [comment]
As always, a minimal reproducible example can drastically speed up the search for the issue cause.

**Comment by xkzl** [comment]
Hello @dancazarin 

While preparing the minimal example, I have found the origin of the issue. It came from my custom elliptic filter implementation. And it is now fixed. Sorry for bothering, thanks for helping !

**Comment by xkzl** [comment]
The conflict came from the use of `kfr::univector<T>` instead of `zpk<T>`
```
univector<complex<T>> z = concatenate(z1, cconj(z2));
univector<complex<T>> p = concatenate(p1, cconj(p2));
T k = (product(-p) / product(-z)).real();
```
replaced by 
```
zpk<T> result;
    result.z = concatenate(z1, cconj(z2));
    result.p = concatenate(p1, cconj(p2));
    result.k = (product(-result.p) / product(-result.z)).real();
```
