### ISSUE TITLE
kfr_dft_real_execute_inverse_f32 creates invalid results on macOS on Intel processors with -Ofast

### ISSUE THREAD

**Issue by FigBug** [kfrlib/kfr#183]
`kfr_dft_real_execute_inverse_f32` creates invalid results on macOS intel processors if -Ofast is used. 

Unfortunately due to a number of broken commits that do not compile, I can not determine exactly when this stopped working. According to git bisect, the first bad commit could between Fri Nov 4 17:47:07 2022 +0000 and Fri Nov 11 19:43:43 2022 +0000.

It only seems to affect certain block sizes.

I will provide a minimal program to reproduce: https://github.com/reFX/kfr_issue

If you compile with Xcode 14.3.1 and run on intel processor, with the -Ofast flag, the output is incorrect. With other optimization levels, output is correct. Output is always correct on ARM processors.

My test program does a series inverse FFts, correct output looks like this:
<img width="712" alt="image" src="https://github.com/kfrlib/kfr/assets/1270305/e20b63f0-35a1-4420-9977-b66176d6b760">

With -Ofast it looks like this:
<img width="712" alt="image" src="https://github.com/kfrlib/kfr/assets/1270305/4830963f-f61b-4285-8cf9-ac313121f13c">

**Comment by FigBug** [comment]
Can't create a standalone program to reproduce the issue, closing until I get more info

**Comment by dancazarin** [comment]
There is a bug in Clang on macOS caused by `-ffast-math` (implied by `-Ofast`) flag.
To workaround this, compile KFR DFT files with `-ffp-contract=fast`.
Other files that use KFR may be compiled with any flags.

**Comment by dancazarin** [comment]
Did you get a chance to test this workaround for Clang bug?

**Comment by dancazarin** [comment]
`-Ofast` is basically `-O3` coupled with `-ffast-math`
Replace `-Ofast` with `-O3 -ffp-contract=fast`
for those files that include KFR DFT.
The performance will be the same as for the fully optimised builds but the bug will go away.

As I mentioned before, `-Ofast` flag causes an internal bug in Clang optimiser.

**Comment by dancazarin** [comment]
Could you provide the output of `xcodebuild` command? This will print compiler options used for each file.
And please update the `kfr_issue` repo if you have made changes to compiler options.
Xcode project in `kfr_issue` has explicit `FAST_MATH` setting turned on as well as `-Ofast` flag. Any of these may cause clang bug.

**Comment by dancazarin** [comment]
Does the error mentioned still occur for you?

**Comment by reFX-Mike** [comment]
No idea when it changed, but with the latest version of Xcode and KFRlib this works correctly now on Arm and Intel. So this issue can be closed.
