### ISSUE TITLE
capi.cpp does not compile on non intel processors

### ISSUE THREAD

**Issue by FigBug** [kfrlib/kfr#184]
The `kfr::dft_plan` constructor that takes a `cpu_t::runtime` is used. This constructor only exists on intel processors.

The following commit works around the issue:
https://github.com/reFX/kfr/commit/ddaa0af7a41849b178481dafd9db8b8d24a745ed

**Comment by dancazarin** [comment]
Fixed from the order size. DFT (and DCT) constructors now always allow `cpu_t` argument regardless of architecture.
