### ISSUE TITLE
std::is_pov deprecated - Visual Studio

### ISSUE THREAD

**Issue by dpieve** [kfrlib/kfr#190]
On Visual Studio 2022, this code works if Platform toolset = `LLVM (clang-cl)`:
```cpp
kfr::univector<f32, 134> taps;
const kfr::expression_handle<f32> window = kfr::to_handle<kfr::expression_kaiser<f32>>(kfr::window_kaiser<f32>(taps.size()));
```

If Platform toolset = `Visual Studio 2022 (v143)`, it gives an error:
```
1>E:\kfr\include\kfr\cometa.hpp(196,42): error C4996: 'std::is_pod_v<cometa::f32>': was declared deprecated
```
The code that originates the error: (file: cometa.hpp)
```
constexpr inline bool is_pod_like = std::is_pod_v<T> || details::is_pod_like_impl<T>::value;
```
`std::is_pod` is [deprecated](https://en.cppreference.com/w/cpp/types/is_pod).
If I comment the `std::is_pod_v<T> ||`, then it compiles.

I have an old project and I can't change it all to LLVM. What should I do in this case to work with VS22 v143?

I'm not sure if I can leave it commented or what would be the equivalent. I would greatly appreciate any help.

#### Project:
/std:c++latest
Visual Studio 2022 - 17.7.2
Kfr 5.0.3
Windows 11 22H2

**Comment by dancazarin** [comment]
C4996 is a warning not an error. 
Do you have 'Treat warnings as errors' setting turned on or `/WX` flag in your project? Anyway, you can suppress this warning to continue using latest VS2022.
As for the deprecation itself, this will be fixed in the next release of KFR.

**Comment by dpieve** [comment]
Indeed, I see it's a warning and not an error. 'Treat warnings as errors' is set to 'No'. I will try to suppress it. 
Thank you for the reply

**Comment by dancazarin** [comment]
Since KFR 5.1.0 (just pushed to dev) `std::is_pod` isn't used, so the C4996 warning/error should gone.

**Comment by dpieve** [comment]
Hey @dancazarin, KFR 5.1.0 works fine now. I sincerely appreciate your help. Thank you once again!

**Comment by dpieve** [comment]
Thank you once again! I tested it here, and KFR 5.1.0 and no more warnings. However, I get a compile error in `Release x64` when I have the following code with Platform toolset `VS22 v143:`

```cpp
#include "kfr/all.hpp"

int main() {
	univector<f32, 127> taps;
	const expression_handle<f32> window = kfr::to_handle<expression_blackman_harris<f32>>(kfr::window_blackman_harris<f32>(taps.size()));
	return 0;
}
```

It shows error [C1001](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1001?view=msvc-170):
```
PathToKfr\kfr\include\kfr\math\impl\sin_cos.hpp(61): fatal error C1001: Internal compiler error.
```

It compiles in Debug x64

**Comment by dpieve** [comment]
The compiler error mentioned in my previous code only happens if `C/C++ > Optimization > Inline Function Expansion` is enabled.
Only when `Inline Function Expansion` is `Disabled (/Ob0)`, the compiler error doesn't occur.

**Comment by dancazarin** [comment]
Could you provide the exact version of VS compiler? `cl --version` in VS shell.

**Comment by dpieve** [comment]
> Could you provide the exact version of VS compiler? `cl --version` in VS shell.

Yes. Compiler version: 19.37.32822 for x86.
VS is 17.7.2, version 4.8.09032.

**Comment by dancazarin** [comment]
The fix for Visual Studio compiler error has been implemented in `dev` branch. Could you test it in your environment?

**Comment by dpieve** [comment]
It works in my environment. I compiled it in Debug and Release x64 mode. The compiler error was fixed. Thank you.

**Comment by dancazarin** [comment]
The ICE has been fixed using more robust method. Already in `main`. Please pull new changes in case this ICE happens again.
