### ISSUE TITLE
‘__rdtsc’ was not declared in this scope on ARMv6

### ISSUE THREAD

**Issue by skadge** [kfrlib/kfr#20]
When compiling `kfr` with `gcc-6.3` on the raspberrypi (`ARMv6` architecture), compilation fails with the following error:

```
kfr/include/kfr/base/random.hpp: In constructor ‘kfr::random_bit_generator::random_bit_generator(kfr::seed_from_rdtsc_t)’:
kfr/include/kfr/base/random.hpp:46:48: error: ‘__rdtsc’ was not declared in this scope
 #define KFR_builtin_readcyclecounter() __rdtsc()
                                                ^
kfr/include/kfr/base/random.hpp:52:42: note: in expansion of macro ‘KFR_builtin_readcyclecounter’
         : state(bitcast<u32>(make_vector(KFR_builtin_readcyclecounter(),
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by skadge** [comment]
One solution would be to use a specific cycle counting function for the ARM processors, like [here](https://blog.regehr.org/archives/794).

**Comment by dlevin256** [comment]
Hi,

This solution requires the PMCCNTR reading instruction to be enabled by the kernel.
In KFR, cycle counter is used only to initialize random number generator.
So it may be replaced by any thread-safe function returning random-like values.

**Comment by dlevin256** [comment]
`KFR_DISABLE_READCYCLECOUNTER` can now be used to disable __builtin_readcyclecounter/__rdtsc
