### ISSUE TITLE
Combine FIR filters in parallel

### ISSUE THREAD

**Issue by idotta** [kfrlib/kfr#204]
This might be off-topic, but can you please confirm if, for having the same effect of applying two different filters, I just have to sum the coefficients in the taps? For example:
```
univector<fbase> tapsNotch(NumTaps);
univector<fbase> tapsBP(NumTaps);
fir_bandstop(tapsNotch, fn1, fn2, window, true);
fir_bandpass(tapsBP,  fbp1, fbp2, window, true);
filter_fir<fbase, fbase> parallelFilter(tapsNotch + tapsBP); // just a simplification
```

**Comment by dancazarin** [comment]
Yes, applying a filter that is the sum of coefficients of two filters is the same as applying two filters _in parallel_ (equaliser-like). For filters _in series_ you would need a convolution of two coefficient vectors.

**Comment by idotta** [comment]
Wow, thanks for the fast and clarifying response!
