### ISSUE TITLE
using std::complex

### ISSUE THREAD

**Issue by xkzl** [kfrlib/kfr#206]
Hi @dancazarin 

Is there any disadvantage to enable/disable `-DKFR_STD_COMPLEX` ?
Why is there such custom types and what would be your recommendation ?

**Comment by dancazarin** [comment]
In versions before KFR5 there were differences in SIMD operations with std::complex and kfr::complex. Since KFR5 there are no more differences/disadvantages. Since KFR6 `KFR_STD_COMPLEX` and kfr::complex will be removed in favor of using std::complex everywhere.
