### ISSUE TITLE
[Planner Flags] FFTW_* option equivalent

### ISSUE THREAD

**Issue by xkzl** [kfrlib/kfr#207]
Hello,

Is there any equivalent in KFR5 (or 6) to the FFTW3 planner flag options ?
https://www.fftw.org/fftw3_doc/Planner-Flags.html

(e.g. `FFTW_ESTIMATE`, `FFTW_PATIENT`, `FFTW_MEASURE`, `FFTW_EXHAUSTIVE`)

Thank you

**Comment by dancazarin** [comment]
Hello,

There is no direct equivalent in KFR. KFR doesn't use such options and have predefined DFT plans that provide maximum performance for each architecture.
