### ISSUE TITLE
Documentation: IO, audio formats

### ISSUE THREAD

**Issue by efremale** [kfrlib/kfr#21]
Hi,

is there any documentation/examples on how to read input from a file or convert existing data to KFR data types? 

What audio formats are supported?

Thank you.

**Comment by dlevin256** [comment]
Hi,
Currently only raw file reading/writing and WAV file writing is fully supported in KFR.
Reading/writing of AIFF and WAV files are planned for future releases.

Or you can read/write audio using any appropriate library and `kfr::univector` as a storage type.
