### ISSUE TITLE
KFR_STD_COMPLEX causes C2386 in Visual Studio 2017

### ISSUE THREAD

**Issue by twoz** [kfrlib/kfr#22]
When trying to define `KFR_STD_COMPLEX`, I get the following error;

> 1>kfr-master\include\kfr\base\complex.hpp(51): error C2386: 'complex': a symbol with this name already exists in the current scope

My specifications: 
Windows 10
Visual Studio 2017
`_MSV_VER` == 1910

Minimum reproduction code:
```
#define KFR_STD_COMPLEX
#include "kfr/dsp.hpp"

int main()
{
	return 0;
}
```

**Comment by dlevin256** [comment]
Fixed
