### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [kfrlib/kfr#23]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by tjwrona1992** [comment]
I agree, I would love to see this available through Conan without having to figure out how to roll my own package.

**Comment by bmanga** [comment]
seems to be in [public-conan](https://bintray.com/bincrafters/public-conan/kfr%3Abincrafters)
