### ISSUE TITLE
take  a long  time

### ISSUE THREAD

**Issue by dowerwang** [kfrlib/kfr#232]
![image](https://github.com/user-attachments/assets/49d2c8bb-632b-45a9-82c6-404c5dd770c3)
![a3f3a4cb2995ba5d5ebc5257cafddaa](https://github.com/user-attachments/assets/d74a5fc0-04a7-436a-9700-0ca70d78aae7)

**Comment by dancazarin** [comment]
Move the following line that designs the IIR filter out of the cycle:
```
zpk<fbase> filt = iir_lowpass(butterworth<fbase>(10), 150, 400);
```
The filter design functions must be called only once and before the start of processing audio.

**Comment by dowerwang** [comment]
![image](https://github.com/user-attachments/assets/6b2c0f9b-143d-4c57-988c-3d6edd3f770c)

**Comment by dancazarin** [comment]
Your benchmark is obviously wrong. You measure elapsed time, convert to **milli**seconds and print as if it was microseconds.

Make and post the screenshot of your Visual Studio toolbar also if possible.

**Comment by dowerwang** [comment]
The dataset consists of 6,900 images, each with a resolution of 255x255 pixels. These images are organized into an array where pixel combinations from the same position are stored as float buff[255][255][6900]. Currently, I am utilizing the Butterworth filter library to conduct low-pass filtering tests; however, I find the processing speed to be excessively slow. Is this performance unreasonable? How can it be optimized?

**Comment by dancazarin** [comment]
To be able to identify the performance bottlenecks I need to see the full source code. You can post it here if it's acceptable for you.
Also I need to know the following values just before the cycle starts:
```
csvData.size()
```

**Comment by dowerwang** [comment]
/**
 * KFR (https://www.kfrlib.com)
 * Copyright (C) 2016-2023 Dan Cazarin
 * See LICENSE.txt for details
 */

#include <kfr/io/tostring.hpp>
#include <kfr/testo/testo.hpp>
#include <kfr/version.hpp>
#ifdef HAVE_MPFR
#include "mpfr/mpfrplus.hpp"
#endif
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>

#include <kfr/base.hpp>
#include <kfr/dsp/biquad.hpp>
#include <kfr/dsp/biquad_design.hpp>
#include <kfr/dsp/special.hpp>
#include <kfr/io.hpp>
using namespace kfr;


std::vector<fbase> readCSV(const std::string& filename)
{
    std::ifstream file(filename);
    int index = 0;
    std::string line;
    std::vector<fbase> data;
    if (!file.is_open())
    {
        std::cerr << "Could not open the file: " << filename << std::endl;
        return data;
    }

    while (std::getline(file, line))
    {
        std::stringstream lineStream(line);
        std::string cell;
       

        while (std::getline(lineStream, cell, ',') )
        {

            data.push_back(std::stof(cell));
            index++;
           
        }
       
    }

    file.close();
    return data;
}
#include <kfr/base.hpp>
#include <kfr/dsp.hpp>
#include <kfr/io.hpp>
#include <chrono>
#include <iostream>

int main()
{
  /*  println(library_version(), " running on ", cpu_runtime());
    try
    {
#ifdef HAVE_MPFR
        mpfr::scoped_precision p(64);
#endif
        return testo::run_all("");
    }
    catch (const std::exception& e)
    {
        errorln("****************************************");
        errorln("***** Exception: ", typeid(e).name(), ": ", e.what());
        return -1;
    }
    catch (...)
    {
        errorln("****************************************");
        errorln("***** Exception: unknown");
        return -1;
    }*/
    std::string filename    = "C:/Users/DELL/Downloads/kfr-main/184412-5602326.csv";
    std::vector<fbase> csvData = readCSV(filename);
   

    std::cout << "data size" << csvData.size() << std::endl; // `size=6900`
    
    univector<fbase> output;
   
    zpk<fbase> filt = iir_lowpass(butterworth<fbase>(10), 150, 400);
    auto start      = std::chrono::high_resolution_clock::now(); 
    for (int i = 0; i < 255 * 255; i++)
    {
       
        output = iir(make_univector(csvData), filt);
    }
    auto end = std::chrono::high_resolution_clock::now();

    std::chrono::duration<double, std::milli> elapsed = end - start; 
    // 计算时间差并转换为ms
   
    std::cout << "Execution time: " << elapsed.count()/1000 
             << " ms" << std::endl;
    std::cout << "output size" << output.size() << std::endl;
    return 0;

  
}

**Comment by dowerwang** [comment]
`/**
 * KFR (https://www.kfrlib.com)
 * Copyright (C) 2016-2023 Dan Cazarin
 * See LICENSE.txt for details
 */

#include <kfr/io/tostring.hpp>
#include <kfr/testo/testo.hpp>
#include <kfr/version.hpp>
#ifdef HAVE_MPFR
#include "mpfr/mpfrplus.hpp"
#endif
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>

#include <kfr/base.hpp>
#include <kfr/dsp/biquad.hpp>
#include <kfr/dsp/biquad_design.hpp>
#include <kfr/dsp/special.hpp>
#include <kfr/io.hpp>
using namespace kfr;


std::vector<fbase> readCSV(const std::string& filename)
{
    std::ifstream file(filename);
    int index = 0;
    std::string line;
    std::vector<fbase> data;
    if (!file.is_open())
    {
        std::cerr << "Could not open the file: " << filename << std::endl;
        return data;
    }

    while (std::getline(file, line))
    {
        std::stringstream lineStream(line);
        std::string cell;
       

        while (std::getline(lineStream, cell, ',') )
        {

            data.push_back(std::stof(cell));
            index++;
           
        }
       
    }

    file.close();
    return data;
}
#include <kfr/base.hpp>
#include <kfr/dsp.hpp>
#include <kfr/io.hpp>
#include <chrono>
#include <iostream>

int main()
{
  
    std::string filename    = "C:/Users/DELL/Downloads/kfr-main/184412-5602326.csv";
    std::vector<fbase> csvData = readCSV(filename);
   

    std::cout << "data size" << csvData.size() << std::endl; //6900
    
    univector<fbase> output;
   
    zpk<fbase> filt = iir_lowpass(butterworth<fbase>(10), 150, 400);
    auto start      = std::chrono::high_resolution_clock::now(); 
    for (int i = 0; i < 255 * 255; i++)
    {
       
        output = iir(make_univector(csvData), filt);
    }
    auto end = std::chrono::high_resolution_clock::now();

    std::chrono::duration<double, std::milli> elapsed = end - start; 
    // 计算时间差并转换为ms
   
    std::cout << "Execution time: " << elapsed.count()/1000 
             << " ms" << std::endl;
    std::cout << "output size" << output.size() << std::endl;
    return 0;

  
}
`

**Comment by dowerwang** [comment]
[184412-5602326.csv](https://github.com/user-attachments/files/16987927/184412-5602326.csv)

**Comment by dancazarin** [comment]
Make sure that you use Release config for benchmarking. Only Release builds are optimized for fast execution.
x64 is required for faster processing as well.

**Comment by dowerwang** [comment]
![image](https://github.com/user-attachments/assets/5f6bc5fa-0306-4ae3-b762-1b6f602c7792)

**Comment by dowerwang** [comment]
Thank you, the release version is much faster now. 
![image](https://github.com/user-attachments/assets/2e784960-9934-4492-9858-fac8865065b1)

**Comment by dowerwang** [comment]
![image](https://github.com/user-attachments/assets/c71d1d8b-6828-4f5f-b507-661b1c38632d)

**Comment by dancazarin** [comment]
What is the difference between the code that executed in 4.7791 ms and the code that executed in 4995.33 ms?

**Comment by dancazarin** [comment]
Also add the following line to the beginning of main:
```
    println(library_version()); // Print the version of the KFR
```

**Comment by dowerwang** [comment]
Sorry, it's all 4.x seconds, the time unit is wrong.
