### ISSUE TITLE
Build fails for LLVM 19 / Windows

### ISSUE THREAD

**Issue by MarcKamradt** [kfrlib/kfr#234]
It seems the function 

```
    template <size_t index, typename = void,
              KFR_ENABLE_IF(index < 1024 && !compound_type_traits<T>::is_scalar)>
    KFR_MEM_INTRINSIC constexpr void set(csize_t<index>, const value_type& s) CMT_NOEXCEPT
    {
        this->s[index] = s;
    }

```

does not compile with the latest LLVM. It looks like clang never evaluated it before because of the KFR_ENABLE_IF and they now have changed the behavior and the compilation fails.

**Comment by reFX-Mike** [comment]
The affected file is `include/kfr/simd/vec.hpp`. This is a show-stopper for us.

**Comment by dancazarin** [comment]
Fixed in `dev` branch.
