### ISSUE TITLE
build error on raspberry pi

### ISSUE THREAD

**Issue by cogmeta** [kfrlib/kfr#25]
python build.py 
threads =  1
-- Clang found
-- C++ compiler: Clang 3.8.1 /usr/bin/clang++-3.8 
-- Could NOT find MPFR (missing:  MPFR_INCLUDE_DIR MPFR_LIBRARIES) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/exp/assistant-sdk-cpp/vendor/kfr/build
[  3%] Building CXX object examples/CMakeFiles/biquads.dir/biquads.cpp.o
Stack dump:
0.	Program arguments: /usr/lib/llvm-3.8/bin/clang -cc1 -triple armv6kz--linux-gnueabihf -emit-obj -disable-free -disable-llvm-verifier -main-file-name biquads.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu arm1176jzf-s -target-feature +strict-align -target-abi aapcs-linux -mfloat-abi hard -dwarf-column-info -debugger-tuning=gdb -coverage-file /home/pi/exp/assistant-sdk-cpp/vendor/kfr/build/examples/CMakeFiles/biquads.dir/biquads.cpp.o -resource-dir /usr/lib/llvm-3.8/bin/../lib/clang/3.8.1 -I /home/pi/exp/assistant-sdk-cpp/vendor/kfr/examples/../include -D NDEBUG -internal-isystem /usr/bin/../lib/gcc/arm-linux-gnueabihf/6.3.0/../../../../include/c++/6.3.0 -internal-isystem /usr/bin/../lib/gcc/arm-linux-gnueabihf/6.3.0/../../../../include/arm-linux-gnueabihf/c++/6.3.0 -internal-isystem /usr/bin/../lib/gcc/arm-linux-gnueabihf/6.3.0/../../../../include/arm-linux-gnueabihf/c++/6.3.0 -internal-isystem /usr/bin/../lib/gcc/arm-linux-gnueabihf/6.3.0/../../../../include/c++/6.3.0/backward -internal-isystem /usr/local/include -internal-isystem /usr/lib/llvm-3.8/bin/../lib/clang/3.8.1/include -internal-externc-isystem /usr/include/arm-linux-gnueabihf -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -std=c++1y -fdeprecated-macro -fdebug-compilation-dir /home/pi/exp/assistant-sdk-cpp/vendor/kfr/build/examples -ferror-limit 19 -fmessage-length 128 -fallow-half-arguments-and-returns -fno-rtti -fno-signed-char -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o CMakeFiles/biquads.dir/biquads.cpp.o -x c++ /home/pi/exp/assistant-sdk-cpp/vendor/kfr/examples/biquads.cpp 
1.	/home/pi/exp/assistant-sdk-cpp/vendor/kfr/examples/../include/kfr/base/platform.hpp:76:52: current parser token ';'
2.	/home/pi/exp/assistant-sdk-cpp/vendor/kfr/examples/../include/kfr/base/platform.hpp:30:1: parsing namespace 'kfr'
3.	/home/pi/exp/assistant-sdk-cpp/vendor/kfr/examples/../include/kfr/base/platform.hpp:67:1: parsing namespace 'internal'
clang: error: unable to execute command: Segmentation fault
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.8.1-24+rpi1 (tags/RELEASE_381/final)
Target: armv6--linux-gnueabihf
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/biquads-b58be5.cpp
clang: note: diagnostic msg: /tmp/biquads-b58be5.sh
clang: note: diagnostic msg: 

********************
examples/CMakeFiles/biquads.dir/build.make:62: recipe for target 'examples/CMakeFiles/biquads.dir/biquads.cpp.o' failed
make[2]: *** [examples/CMakeFiles/biquads.dir/biquads.cpp.o] Error 254
CMakeFiles/Makefile2:93: recipe for target 'examples/CMakeFiles/biquads.dir/all' failed
make[1]: *** [examples/CMakeFiles/biquads.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "build.py", line 52, in <module>
    if subprocess.call(['cmake', '--build', '.', '--', '-j' + threads], cwd=build_dir): raise Exception('Can\'t build project')
Exception: Can't build project

**Comment by dlevin256** [comment]
This is a Clang error, not KFR.
> clang: error: unable to execute command: Segmentation fault

You can upgrade clang version to the latest 6.0.0 (four versions since 3.8) to fix this.

This error can also occur due to insufficient memory on device.
In this case cross compiling will help.
