### ISSUE TITLE
Visual Studio Build issues

### ISSUE THREAD

**Issue by keithlostracco** [kfrlib/kfr#26]
Hello, I'm trying to get KFR working in VS2015 but I am having some issues. I get quite a few errors when trying to build the entire solution so I've posted just the output when I try to build the DFT project. 

I'm not overly experienced with C++ so please excuse my ignorance... I'm really excited to process some signals though!

thanks

> 1>------ Build started: Project: dft, Configuration: Debug Win32 ------
1>clang-cl.exe : warning : unknown argument ignored in clang-cl: '-fno-inline' [-Wunknown-argument]
1>clang-cl.exe : warning : argument unused during compilation: '/Gm-' [-Wunused-command-line-argument]
1>  In file included from C:\Users\keith\libraries\kfr-1.2.0\examples\dft.cpp:9:
1>  In file included from C:\Users\keith\libraries\kfr-1.2.0\examples\..\include\kfr/dsp.hpp:34:
1>C:\Users\keith\libraries\kfr-1.2.0\examples\..\include\kfr/dsp/goertzel.hpp(99,16): error : flexible array member 'result' with type 'complex<T> []' is not at the end of struct
1>      complex<T> result[];
1>                 ^
1>  C:\Users\keith\libraries\kfr-1.2.0\examples\..\include\kfr/dsp/goertzel.hpp(100,25):  note: next field declaration is here
1>      const vec<T, width> omega;
1>                          ^
1>  In file included from C:\Users\keith\libraries\kfr-1.2.0\examples\dft.cpp:10:
1>  In file included from C:\Users\keith\libraries\kfr-1.2.0\examples\..\include\kfr/io.hpp:27:
1>  In file included from C:\Users\keith\libraries\kfr-1.2.0\examples\..\include\kfr/io/audiofile.hpp:32:
1>C:\Users\keith\libraries\kfr-1.2.0\examples\..\include\kfr/io/file.hpp(118,56): warning : 'fopen' is deprecated: This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [-Wdeprecated-declarations]
1>      return internal::expression_sequential_file_reader(fopen(file_name.c_str(), "rb"));
1>                                                         ^
1>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\ucrt\stdio.h(206,20):  note: 'fopen' has been explicitly marked deprecated here
1>      _Check_return_ _CRT_INSECURE_DEPRECATE(fopen_s)
1>                     ^
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime.h(269,55):  note: expanded from macro '_CRT_INSECURE_DEPRECATE'
1>          #define _CRT_INSECURE_DEPRECATE(_Replacement) _CRT_DEPRECATE_TEXT(    \
1>                                                        ^
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime.h(259,47):  note: expanded from macro '_CRT_DEPRECATE_TEXT'
1>  #define _CRT_DEPRECATE_TEXT(_Text) __declspec(deprecated(_Text))
1>                                                ^
1>  In file included from C:\Users\keith\libraries\kfr-1.2.0\examples\dft.cpp:10:
1>  In file included from C:\Users\keith\libraries\kfr-1.2.0\examples\..\include\kfr/io.hpp:27:
1>  In file included from C:\Users\keith\libraries\kfr-1.2.0\examples\..\include\kfr/io/audiofile.hpp:32:
1>C:\Users\keith\libraries\kfr-1.2.0\examples\..\include\kfr/io/file.hpp(122,56): warning : 'fopen' is deprecated: This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [-Wdeprecated-declarations]
1>      return internal::expression_sequential_file_writer(fopen(file_name.c_str(), "wb"));
1>                                                         ^
1>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\ucrt\stdio.h(206,20):  note: 'fopen' has been explicitly marked deprecated here
1>      _Check_return_ _CRT_INSECURE_DEPRECATE(fopen_s)
1>                     ^
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime.h(269,55):  note: expanded from macro '_CRT_INSECURE_DEPRECATE'
1>          #define _CRT_INSECURE_DEPRECATE(_Replacement) _CRT_DEPRECATE_TEXT(    \
1>                                                        ^
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime.h(259,47):  note: expanded from macro '_CRT_DEPRECATE_TEXT'
1>  #define _CRT_DEPRECATE_TEXT(_Text) __declspec(deprecated(_Text))
1>                                                ^
1>  2 warnings and 1 error generated.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by dlevin256** [comment]
Fixed
