### ISSUE TITLE
dft_test fails most of the tests in fft_accuracy on macos 10.13.6

### ISSUE THREAD

**Issue by gabrielrussell** [kfrlib/kfr#28]
The results of running python build.py
[build.out.txt](https://github.com/kfrlib/kfr/files/2324718/build.out.txt)

The results of running ./build/bin/dft_test
[dft_test.out.txt](https://github.com/kfrlib/kfr/files/2324720/dft_test.out.txt)

**Comment by dlevin256** [comment]
Hi,

It's Clang bug https://bugs.llvm.org/show_bug.cgi?id=38289
It affects long double conversion which is used in the reference dft implementation (used for comparison).

It does not affect optimized KFR DFT implementation which outputs correct results.

The fix is already in `dev` branch.
