### ISSUE TITLE
Improve the FFT real documentation

### ISSUE THREAD

**Issue by abique** [kfrlib/kfr#3]
Hi,

The documentation for the FFT is a little bit weak to me.

I don't understand very well how works the data layout.

Thank you very much!

**Comment by dlevin256** [comment]
Hi,

A bit more about KFR implementation of the FFT you can find in this blog article:
https://kfrlib.com/blog/fast-fourier-transform-in-c-part-1/

In addition to the CCS format, you can specify the Perm format when you call execute function:
```
dft_plan_real<double> realdft(1024);
realdft.execute(complex_out, real_in, temp, dft_pack_format::Perm);
```

Then, the size of the complex output will be exactly `real_size/2` and the Nyquist frequency (purely real) will be stored in `out[0].imag()`.
Note that you have to specify the same format for forward and backward FFT.

**Comment by abique** [comment]
Hi,

Thank you for the reply!

Idealy this should go into the headers, or doxygen isn't it?

**Comment by dlevin256** [comment]
Yes, in the upcoming release (2.0) the documentation will be added for all the FFT functions and classes.
