### ISSUE TITLE
Add KFR's SRC to Infinite Wave's SRC comparisons

### ISSUE THREAD

**Issue by yairchu** [kfrlib/kfr#30]
[SRC Comparisons](http://src.infinitewave.ca) compares many different libraries and DAWs, and I went there when considering KFR for SRC needs, but did not find it in the list.

If interested, see [their FAQ](http://src.infinitewave.ca/faq.html) on how to contribute the software to SRC Comparisons.

**Comment by dlevin256** [comment]
KFR has been added to the comparison

![](http://src.infinitewave.ca/images/Sweep/KFR3.png)
![](http://src.infinitewave.ca/images/Tone/KFR3.png)

Source: http://src.infinitewave.ca/

**Comment by yairchu** [comment]
Thanks!
