### ISSUE TITLE
Cant't compile with GCC5.4.0 Ubuntu16.40 

### ISSUE THREAD

**Issue by Yablon** [kfrlib/kfr#34]
As the Readme.md, I did the following things:
`mkdir build && cd build`
`cmake -DENABLE_TESTS=ON -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Release ..`
`make`
And get some faults:
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp: In instantiation of 'kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>)::<lambda(auto:15)> [with auto:15 = cometa::cval_t<long unsigned int, 2ul>; bool is_final = true; T = float]':
/home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/../cometa.hpp:1407:18:   required from 'decltype(auto) cometa::cswitch(cometa::cvals_t<T, first, rest ...>, cometa::identity<T>, Fn&&, DefFn&&, CmpFn&&) [with T = long unsigned int; T v0 = 2ul; T ...values = {3ul, 4ul, 5ul, 6ul, 7ul, 8ul, 9ul, 10ul}; Fn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = true; T = float; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, true>]::<lambda(auto:15)>; DefFn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = true; T = float; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, true>]::<lambda()>; CmpFn = cometa::fn_is_equal; cometa::identity<T> = long unsigned int]'
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:1322:19:   required from 'void kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = true; T = float; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, true>]'
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:1544:29:   required from 'kfr::dft_plan<T>::dft_plan(size_t, kfr::dft_order) [with T = float; size_t = long unsigned int]'
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-src.cpp:37:81:   required from here
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:1325:22: error: 'add_stage' was not declared in this scope
             add_stage<conditional<is_final, internal::dft_stage_fixed_final_impl<T, val_of(radix)>,
                      ^
In file included from /home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/types.hpp:40:0,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/constants.hpp:28,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/bitwise.hpp:28,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/operators.hpp:28,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/basic_expressions.hpp:28,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:29,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-src.cpp:27:
/home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/../cometa.hpp: In instantiation of 'decltype(auto) cometa::cswitch(cometa::cvals_t<T, first, rest ...>, cometa::identity<T>, Fn&&, DefFn&&, CmpFn&&) [with T = long unsigned int; T v0 = 2ul; T ...values = {3ul, 4ul, 5ul, 6ul, 7ul, 8ul, 9ul, 10ul}; Fn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = true; T = float; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, true>]::<lambda(auto:15)>; DefFn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = true; T = float; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, true>]::<lambda()>; CmpFn = cometa::fn_is_equal; cometa::identity<T> = long unsigned int]':
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:1322:19:   required from 'void kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = true; T = float; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, true>]'
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:1544:29:   required from 'kfr::dft_plan<T>::dft_plan(size_t, kfr::dft_order) [with T = float; size_t = long unsigned int]'
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-src.cpp:37:81:   required from here
/home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/../cometa.hpp:1411:23: error: use of 'decltype(auto) cometa::cswitch(cometa::cvals_t<T, first, rest ...>, cometa::identity<T>, Fn&&, DefFn&&, CmpFn&&) [with T = long unsigned int; T v0 = 3ul; T ...values = {4ul, 5ul, 6ul, 7ul, 8ul, 9ul, 10ul}; Fn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = true; T = float; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, true>]::<lambda(auto:15)>; DefFn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = true; T = float; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, true>]::<lambda()>; CmpFn = cometa::fn_is_equal; cometa::identity<T> = long unsigned int]' before deduction of 'auto'
         return cswitch(cvals_t<T, values...>(), value, std::forward<Fn>(fn), std::forward<DefFn>(deffn),
                       ^
/home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/../cometa.hpp:1412:50: error: return-statement with a value, in function returning 'void' [-fpermissive]
                        std::forward<CmpFn>(cmpfn));
                                                  ^
In file included from /home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-src.cpp:27:0:
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp: In instantiation of 'kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>)::<lambda(auto:15)> [with auto:15 = cometa::cval_t<long unsigned int, 2ul>; bool is_final = false; T = float]':
/home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/../cometa.hpp:1407:18:   required from 'decltype(auto) cometa::cswitch(cometa::cvals_t<T, first, rest ...>, cometa::identity<T>, Fn&&, DefFn&&, CmpFn&&) [with T = long unsigned int; T v0 = 2ul; T ...values = {3ul, 4ul, 5ul, 6ul, 7ul, 8ul, 9ul, 10ul}; Fn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = false; T = float; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, false>]::<lambda(auto:15)>; DefFn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = false; T = float; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, false>]::<lambda()>; CmpFn = cometa::fn_is_equal; cometa::identity<T> = long unsigned int]'
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:1322:19:   required from 'void kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = false; T = float; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, false>]'
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:1546:29:   required from 'kfr::dft_plan<T>::dft_plan(size_t, kfr::dft_order) [with T = float; size_t = long unsigned int]'
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-src.cpp:37:81:   required from here
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:1325:22: error: 'add_stage' was not declared in this scope
             add_stage<conditional<is_final, internal::dft_stage_fixed_final_impl<T, val_of(radix)>,
                      ^
In file included from /home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/types.hpp:40:0,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/constants.hpp:28,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/bitwise.hpp:28,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/operators.hpp:28,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/basic_expressions.hpp:28,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:29,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-src.cpp:27:
/home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/../cometa.hpp: In instantiation of 'decltype(auto) cometa::cswitch(cometa::cvals_t<T, first, rest ...>, cometa::identity<T>, Fn&&, DefFn&&, CmpFn&&) [with T = long unsigned int; T v0 = 2ul; T ...values = {3ul, 4ul, 5ul, 6ul, 7ul, 8ul, 9ul, 10ul}; Fn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = false; T = float; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, false>]::<lambda(auto:15)>; DefFn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = false; T = float; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, false>]::<lambda()>; CmpFn = cometa::fn_is_equal; cometa::identity<T> = long unsigned int]':
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:1322:19:   required from 'void kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = false; T = float; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, false>]'
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:1546:29:   required from 'kfr::dft_plan<T>::dft_plan(size_t, kfr::dft_order) [with T = float; size_t = long unsigned int]'
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-src.cpp:37:81:   required from here
/home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/../cometa.hpp:1411:23: error: use of 'decltype(auto) cometa::cswitch(cometa::cvals_t<T, first, rest ...>, cometa::identity<T>, Fn&&, DefFn&&, CmpFn&&) [with T = long unsigned int; T v0 = 3ul; T ...values = {4ul, 5ul, 6ul, 7ul, 8ul, 9ul, 10ul}; Fn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = false; T = float; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, false>]::<lambda(auto:15)>; DefFn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = false; T = float; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, false>]::<lambda()>; CmpFn = cometa::fn_is_equal; cometa::identity<T> = long unsigned int]' before deduction of 'auto'
         return cswitch(cvals_t<T, values...>(), value, std::forward<Fn>(fn), std::forward<DefFn>(deffn),
                       ^
/home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/../cometa.hpp:1412:50: error: return-statement with a value, in function returning 'void' [-fpermissive]
                        std::forward<CmpFn>(cmpfn));
                                                  ^
In file included from /home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-src.cpp:27:0:
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp: In instantiation of 'kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>)::<lambda(auto:15)> [with auto:15 = cometa::cval_t<long unsigned int, 2ul>; bool is_final = true; T = double]':
/home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/../cometa.hpp:1407:18:   required from 'decltype(auto) cometa::cswitch(cometa::cvals_t<T, first, rest ...>, cometa::identity<T>, Fn&&, DefFn&&, CmpFn&&) [with T = long unsigned int; T v0 = 2ul; T ...values = {3ul, 4ul, 5ul, 6ul, 7ul, 8ul, 9ul, 10ul}; Fn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = true; T = double; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, true>]::<lambda(auto:15)>; DefFn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = true; T = double; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, true>]::<lambda()>; CmpFn = cometa::fn_is_equal; cometa::identity<T> = long unsigned int]'
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:1322:19:   required from 'void kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = true; T = double; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, true>]'
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:1544:29:   required from 'kfr::dft_plan<T>::dft_plan(size_t, kfr::dft_order) [with T = double; size_t = long unsigned int]'
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-src.cpp:41:82:   required from here
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:1325:22: error: 'add_stage' was not declared in this scope
             add_stage<conditional<is_final, internal::dft_stage_fixed_final_impl<T, val_of(radix)>,
                      ^
In file included from /home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/types.hpp:40:0,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/constants.hpp:28,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/bitwise.hpp:28,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/operators.hpp:28,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/basic_expressions.hpp:28,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:29,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-src.cpp:27:
/home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/../cometa.hpp: In instantiation of 'decltype(auto) cometa::cswitch(cometa::cvals_t<T, first, rest ...>, cometa::identity<T>, Fn&&, DefFn&&, CmpFn&&) [with T = long unsigned int; T v0 = 2ul; T ...values = {3ul, 4ul, 5ul, 6ul, 7ul, 8ul, 9ul, 10ul}; Fn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = true; T = double; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, true>]::<lambda(auto:15)>; DefFn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = true; T = double; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, true>]::<lambda()>; CmpFn = cometa::fn_is_equal; cometa::identity<T> = long unsigned int]':
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:1322:19:   required from 'void kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = true; T = double; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, true>]'
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:1544:29:   required from 'kfr::dft_plan<T>::dft_plan(size_t, kfr::dft_order) [with T = double; size_t = long unsigned int]'
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-src.cpp:41:82:   required from here
/home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/../cometa.hpp:1411:23: error: use of 'decltype(auto) cometa::cswitch(cometa::cvals_t<T, first, rest ...>, cometa::identity<T>, Fn&&, DefFn&&, CmpFn&&) [with T = long unsigned int; T v0 = 3ul; T ...values = {4ul, 5ul, 6ul, 7ul, 8ul, 9ul, 10ul}; Fn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = true; T = double; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, true>]::<lambda(auto:15)>; DefFn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = true; T = double; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, true>]::<lambda()>; CmpFn = cometa::fn_is_equal; cometa::identity<T> = long unsigned int]' before deduction of 'auto'
         return cswitch(cvals_t<T, values...>(), value, std::forward<Fn>(fn), std::forward<DefFn>(deffn),
                       ^
/home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/../cometa.hpp:1412:50: error: return-statement with a value, in function returning 'void' [-fpermissive]
                        std::forward<CmpFn>(cmpfn));
                                                  ^
In file included from /home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-src.cpp:27:0:
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp: In instantiation of 'kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>)::<lambda(auto:15)> [with auto:15 = cometa::cval_t<long unsigned int, 2ul>; bool is_final = false; T = double]':
/home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/../cometa.hpp:1407:18:   required from 'decltype(auto) cometa::cswitch(cometa::cvals_t<T, first, rest ...>, cometa::identity<T>, Fn&&, DefFn&&, CmpFn&&) [with T = long unsigned int; T v0 = 2ul; T ...values = {3ul, 4ul, 5ul, 6ul, 7ul, 8ul, 9ul, 10ul}; Fn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = false; T = double; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, false>]::<lambda(auto:15)>; DefFn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = false; T = double; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, false>]::<lambda()>; CmpFn = cometa::fn_is_equal; cometa::identity<T> = long unsigned int]'
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:1322:19:   required from 'void kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = false; T = double; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, false>]'
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:1546:29:   required from 'kfr::dft_plan<T>::dft_plan(size_t, kfr::dft_order) [with T = double; size_t = long unsigned int]'
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-src.cpp:41:82:   required from here
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:1325:22: error: 'add_stage' was not declared in this scope
             add_stage<conditional<is_final, internal::dft_stage_fixed_final_impl<T, val_of(radix)>,
                      ^
In file included from /home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/types.hpp:40:0,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/constants.hpp:28,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/bitwise.hpp:28,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/operators.hpp:28,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/basic_expressions.hpp:28,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:29,
                 from /home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-src.cpp:27:
/home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/../cometa.hpp: In instantiation of 'decltype(auto) cometa::cswitch(cometa::cvals_t<T, first, rest ...>, cometa::identity<T>, Fn&&, DefFn&&, CmpFn&&) [with T = long unsigned int; T v0 = 2ul; T ...values = {3ul, 4ul, 5ul, 6ul, 7ul, 8ul, 9ul, 10ul}; Fn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = false; T = double; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, false>]::<lambda(auto:15)>; DefFn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = false; T = double; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, false>]::<lambda()>; CmpFn = cometa::fn_is_equal; cometa::identity<T> = long unsigned int]':
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:1322:19:   required from 'void kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = false; T = double; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, false>]'
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:1546:29:   required from 'kfr::dft_plan<T>::dft_plan(size_t, kfr::dft_order) [with T = double; size_t = long unsigned int]'
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-src.cpp:41:82:   required from here
/home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/../cometa.hpp:1411:23: error: use of 'decltype(auto) cometa::cswitch(cometa::cvals_t<T, first, rest ...>, cometa::identity<T>, Fn&&, DefFn&&, CmpFn&&) [with T = long unsigned int; T v0 = 3ul; T ...values = {4ul, 5ul, 6ul, 7ul, 8ul, 9ul, 10ul}; Fn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = false; T = double; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, false>]::<lambda(auto:15)>; DefFn = kfr::dft_plan<T>::prepare_dft_stage(size_t, size_t, size_t, cometa::cbool_t<aligned>) [with bool is_final = false; T = double; size_t = long unsigned int; cometa::cbool_t<aligned> = cometa::cval_t<bool, false>]::<lambda()>; CmpFn = cometa::fn_is_equal; cometa::identity<T> = long unsigned int]' before deduction of 'auto'
         return cswitch(cvals_t<T, values...>(), value, std::forward<Fn>(fn), std::forward<DefFn>(deffn),
                       ^
/home/yablon/some_fun/kfr/include/kfr/dft/impl/../../base/../cometa.hpp:1412:50: error: return-statement with a value, in function returning 'void' [-fpermissive]
                        std::forward<CmpFn>(cmpfn));
                                                  ^
/home/yablon/some_fun/kfr/include/kfr/dft/impl/dft-impl.hpp:1631: confused by earlier errors, bailing out
CMakeFiles/kfr_dft.dir/build.make:62: recipe for target 'CMakeFiles/kfr_dft.dir/include/kfr/dft/impl/dft-src.cpp.o' failed
make[2]: *** [CMakeFiles/kfr_dft.dir/include/kfr/dft/impl/dft-src.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/kfr_dft.dir/all' failed
make[1]: *** [CMakeFiles/kfr_dft.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Can you help me out? Thank you!

**Comment by dlevin256** [comment]
Hi,

GCC 5.x is not fully supported due to some C++14 related bugs in GCC 5-7.
These bugs have been fixes in GCC 8 which is supported in KFR.

There are workarounds for these bugs so support for GCC versions prior to 8 may be added later..

**Comment by Yablon** [comment]
@dlevin256 Thanks!
