### ISSUE TITLE
Intellisense issue on Visual Studio 2017

### ISSUE THREAD

**Issue by KarlL2** [kfrlib/kfr#40]
I'm using kfr on Visual Studio 2017. It works well, but intellisense either doesn't work or is extremely slow. Types are often not colored/detected, pressing F12 to go to the definition of a type (either a type from KFR or other library) always brings a loading bar that often never disappears, ...

Has anyone experienced this or has tips on how to fix it? I tried removing all the KFR files that I didn't need in the `include` folder, but it didn't seem to really help.

**Comment by dlevin256** [comment]
Yes, it's known, solution is in progress.

**Comment by dlevin256** [comment]
Fixed in master branch.
