### ISSUE TITLE
Release 3.0.5 breaks Android Support

### ISSUE THREAD

**Issue by Jman420** [kfrlib/kfr#41]
Due to a custom implementation of pthreads in Android the latest release of KFR can not easily be included in an Android.  The 3.0.5 release currently results in a build error of 'cannot find -lpthread' when adding KFR to CMakeList using add_subdirectory().

https://developer.android.com/ndk/guides/stable_apis#clib

Edit : I've added a branch in my project to illustrate the issue : https://github.com/Jman420/menrva/tree/feature/upgrade-kfr

**Comment by Jman420** [comment]
Update - I've managed to workaround the 'cannot find -lpthread' error by using the attached CMakeList for KFR.  And by ensuring that 'libc++_shared.so' gets included in my APK by adding the following line to the defaultSettings cmake section of my app's gradle build script : arguments "-DANDROID_STL=c++_shared".

But unfortunately now I get SIGILL errors at runtime even in tests when I do not use KFR.  The SIGILL is raised on this line : https://github.com/kfrlib/kfr/blob/0907b9254786d5008dd6e33c33cdfff21d8c8585/include/kfr/simd/vec.hpp#L224
[CMakeLists.txt](https://github.com/kfrlib/kfr/files/2923151/CMakeLists.txt)

**Comment by dlevin256** [comment]
Hi,

Thank you for suggested change. Can you make pull request?

In the new version, default architecture in KFR is AVX2 for x86.
If AVX2 is not supported by your CPU, set `CPU_ARCH` cmake variable to the name of the target architecture.
One of:
```
avx512
avx2
avx
sse42
sse41
ssse3
sse3
sse2
generic
```
This needs to be done only for x86 mode.

Or set `CPU_ARCH` to `detect`, then KFR will try to detect cpu capabilities before building any code.

**Comment by Jman420** [comment]
Sure, PR incoming for the pthread fix.

I'll play around with the CPU_ARCH; I'm definitely using x86 mode in my testing and will be distributing the standard Android architectures (x86, x86_64, arm64-v8a and armeabi-v7a).  Will post results from CPU_ARCH experiments here.

**Comment by Jman420** [comment]
Great news!  The CPU_ARCH suggestion worked.  I'll have another PR coming shortly to incorporate that fix as well.

For reference I looked up the supported Android instruction sets here : https://developer.android.com/ndk/guides/abis.html#sa

**Comment by triplef** [comment]
@Jman420 did you already get a chance to submit that PR for `CPU_ARCH`? I’m running into what I think is the same issue compiling for Android, where the CPU_ARCH auto-detection won’t work due to cross-compiling mode.
