### ISSUE TITLE
audio mixer

### ISSUE THREAD

**Issue by mipac** [kfrlib/kfr#49]
I try to mix multiple mono audio to one channel output.
is kfr have an api to do that efficiently ?

**Comment by dlevin256** [comment]
Hi,
If you mean downmixing mono to mono, then here is the code:
```
make_univector(pointer_to_output_channel, size_in_samples) = 
        make_univector(pointer_to_first_channel, size_in_samples) +
        make_univector(pointer_to_second_channel, size_in_samples) +
        make_univector(pointer_to_third_channel, size_in_samples);
```

if you need to adjust gain for each channel, then:
```
make_univector(pointer_to_output_channel, size_in_samples) = 
        first_gain  * make_univector(pointer_to_first_channel, size_in_samples) +
        second_gain * make_univector(pointer_to_second_channel, size_in_samples) +
        third_gain  * make_univector(pointer_to_third_channel, size_in_samples);
```
Use `dB_to_amp` if you have gain in decibels.

Or do you need to downmix mono to stereo using gain and pan for each channel?

pointers are `float*` or `double*`.

**Comment by mipac** [comment]
hi, thanx for reply
well my question was so badly formulated (and my english so strange ;)

i mean, when simply sum, we need to rescale
and certainly normalize the output level

if i sum 10 "tracks" and 8 are at noise level, I wanna hear "clearly" the 2 actives

so I thought about something like agc or compressor or limiter or "state of the art" tweak 😅

I saw ebu loudness api, but after some search it does't seem to be related to this kind of purpose
