### ISSUE TITLE
KFR_STD_COMPLEX causes error : call to implicitly-deleted default constructor of 'vec<..>'

### ISSUE THREAD

**Issue by Ultrafeel** [kfrlib/kfr#53]
When trying to define KFR_STD_COMPLEX and compile .lib of kfr_dfc, I get the following error;

>     error : call to implicitly-deleted default constructor of 'vec<kfr::sse2::internal::expression_padded<kfr::sse2::internal::expression_function<kfr::sse2::fn::div, int, kfr::sse2::internal::expression_slice<kfr::univector<std::complex<float>, 4294967295> &> > >::value_type, 4U>' (aka 'vec<std::complex<float>, 4U>')

My specifications:
Windows 7
Visual Studio 2017

**Comment by dlevin256** [comment]
KFR DFT requires Clang compiler (or LLVM toolchain for MSVC).
Do you use it?
