### ISSUE TITLE
cannot sync with Android Studio    install TARGETS given no LIBRARY DESTINATION for shared library target

### ISSUE THREAD

**Issue by mgood7123** [kfrlib/kfr#55]
debug|armeabi-v7a :-- CMAKE_CXX_FLAGS=-g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security   -v -std=c++17 -v -std=c++17 -v -std=c++17
debug|armeabi-v7a :-- CMAKE_CXX_FLAGS= -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security   -v -std=c++17 -v -std=c++17 -v -std=c++17
debug|armeabi-v7a :-- C++ compiler: Clang 8.0 C:/Users/konek/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe 
debug|armeabi-v7a :-- CMAKE_SYSTEM_PROCESSOR=armv7-a
debug|armeabi-v7a :-- CPU_ARCH=detect
debug|armeabi-v7a :CMake Error at resampler/kfr/CMakeLists.txt:181 (install):
debug|armeabi-v7a :  install TARGETS given no LIBRARY DESTINATION for shared library target
debug|armeabi-v7a :  "kfr_io".
debug|armeabi-v7a :CMake Error at resampler/kfr/CMakeLists.txt:184 (install):
debug|armeabi-v7a :  install TARGETS given no LIBRARY DESTINATION for shared library target
debug|armeabi-v7a :  "kfr_dft".
debug|armeabi-v7a :-- Configuring incomplete, errors occurred!
debug|armeabi-v7a :See also "C:/Users/konek/StudioProjects/libmedia/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeOutput.log".
debug|armeabi-v7a :See also "C:/Users/konek/StudioProjects/libmedia/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeError.log".
debug|arm64-v8a :-- CMAKE_CXX_FLAGS=-g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security   -v -std=c++17 -v -std=c++17 -v -std=c++17
debug|arm64-v8a :-- CMAKE_CXX_FLAGS= -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security   -v -std=c++17 -v -std=c++17 -v -std=c++17
debug|arm64-v8a :-- C++ compiler: Clang 8.0 C:/Users/konek/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe 
debug|arm64-v8a :-- CMAKE_SYSTEM_PROCESSOR=aarch64
debug|arm64-v8a :-- CPU_ARCH=detect
debug|arm64-v8a :CMake Error at resampler/kfr/CMakeLists.txt:181 (install):
debug|arm64-v8a :  install TARGETS given no LIBRARY DESTINATION for shared library target
debug|arm64-v8a :  "kfr_io".
debug|arm64-v8a :CMake Error at resampler/kfr/CMakeLists.txt:184 (install):
debug|arm64-v8a :  install TARGETS given no LIBRARY DESTINATION for shared library target
debug|arm64-v8a :  "kfr_dft".
debug|arm64-v8a :-- Configuring incomplete, errors occurred!
debug|arm64-v8a :See also "C:/Users/konek/StudioProjects/libmedia/app/.externalNativeBuild/cmake/debug/arm64-v8a/CMakeFiles/CMakeOutput.log".
debug|arm64-v8a :See also "C:/Users/konek/StudioProjects/libmedia/app/.externalNativeBuild/cmake/debug/arm64-v8a/CMakeFiles/CMakeError.log".
release|armeabi-v7a :-- CMAKE_CXX_FLAGS=-g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security   -v -std=c++17 -v -std=c++17 -v -std=c++17
release|armeabi-v7a :-- CMAKE_CXX_FLAGS= -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security   -v -std=c++17 -v -std=c++17 -v -std=c++17
release|arm64-v8a :-- CMAKE_CXX_FLAGS=-g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security   -v -std=c++17 -v -std=c++17 -v -std=c++17
release|arm64-v8a :-- CMAKE_CXX_FLAGS= -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security   -v -std=c++17 -v -std=c++17 -v -std=c++17
release|armeabi-v7a :-- C++ compiler: Clang 8.0 C:/Users/konek/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe 
release|armeabi-v7a :-- CMAKE_SYSTEM_PROCESSOR=armv7-a
release|armeabi-v7a :-- CPU_ARCH=detect
release|armeabi-v7a :CMake Error at resampler/kfr/CMakeLists.txt:181 (install):
release|armeabi-v7a :  install TARGETS given no LIBRARY DESTINATION for shared library target
release|armeabi-v7a :  "kfr_io".
release|armeabi-v7a :CMake Error at resampler/kfr/CMakeLists.txt:184 (install):
release|armeabi-v7a :  install TARGETS given no LIBRARY DESTINATION for shared library target
release|armeabi-v7a :  "kfr_dft".
release|arm64-v8a :-- C++ compiler: Clang 8.0 C:/Users/konek/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe 
release|arm64-v8a :-- CMAKE_SYSTEM_PROCESSOR=aarch64
release|armeabi-v7a :-- Configuring incomplete, errors occurred!
release|armeabi-v7a :See also "C:/Users/konek/StudioProjects/libmedia/app/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeOutput.log".
release|armeabi-v7a :See also "C:/Users/konek/StudioProjects/libmedia/app/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeError.log".
release|arm64-v8a :-- CPU_ARCH=detect
release|arm64-v8a :CMake Error at resampler/kfr/CMakeLists.txt:181 (install):
release|arm64-v8a :  install TARGETS given no LIBRARY DESTINATION for shared library target
release|arm64-v8a :  "kfr_io".
release|arm64-v8a :CMake Error at resampler/kfr/CMakeLists.txt:184 (install):
release|arm64-v8a :  install TARGETS given no LIBRARY DESTINATION for shared library target
release|arm64-v8a :  "kfr_dft".
release|arm64-v8a :-- Configuring incomplete, errors occurred!
release|arm64-v8a :See also "C:/Users/konek/StudioProjects/libmedia/app/.externalNativeBuild/cmake/release/arm64-v8a/CMakeFiles/CMakeOutput.log".
release|arm64-v8a :See also "C:/Users/konek/StudioProjects/libmedia/app/.externalNativeBuild/cmake/release/arm64-v8a/CMakeFiles/CMakeError.log".

**Comment by dlevin256** [comment]
Check again using `dev` branch

**Comment by dlevin256** [comment]
Reopen if the issue persists.
