### ISSUE TITLE
[Implementation] Implementing a simple low pass filter

### ISSUE THREAD

**Issue by acxz** [kfrlib/kfr#59]
I would like to use this library to implementing a low pass filter, instead of writing my own low pass filter, however, after spending some time looking at the examples and the documentation I am a bit lost in whether I can achieve what I want with kfr. If anyone could help me/point me in the right direction it would be much appreciated. Forgive me for my naivety I am not too exposed to DSP.

Problem:
I am receiving a data stream of samples (digital, just doubles) along with their associated timestamps. When I sample this data stream the data is noisy, as such I would like convert the sampled output of the data stream to a filtered less noisy sample, say filtering out data greater than some cutoff frequency.
Note: I would not like to keep track of all the previous samples, (I know I need to keep track of the previous sample based on (1st order) low pass filter equations I am familiar with).

From what I understand so far I can design parameters (taps) for a filter at specific cutoff frequencies and with a window method. However, after reading and running the example code on `fir.cpp` and looking at the output images (amplitude and gain plots) I am not sure what the cutoff value actually means. It does not seem to represent cutoff frequencies for a filter.

From the output taps of designing the filter I can create a filter. Now my question is how I can use my filter on individual samples rather than the entire datastream. When I use `filter.apply(output, input)` can my input be a single sample? Another question I have is how to incorporate the associated timestamps along with the incoming samples? This information is vital for outputting a filtered sample.

After some more research it seems that an IIR filter is a solution to my problem instead of a FIR filter. However, kfr does not seem to have any implementations of IIR filters, however there are biquad implementations, but I am still not sure how to specify my dt when I apply the filter on a single sample.

As for the cutoff value, I know understand that to be the ratio: freq_cutoff/freq_sampling.

**Comment by acxz** [comment]
I ended up solving my issue. If anyone would like further discussion on this you can go ahead and reopen this issue.

**Comment by chrisdukey** [comment]
@acxz I'm looking to do something very similar to what you've done and was wondering if there's any chance you have a sample piece of code you could share that would point me in the right direction? Many thanks.

**Comment by dlevin256** [comment]
@chrisdukey ,
If you need IIR filter, now KFR has implementation for IIR filter design (since KFR 4.0) - butterworth, chebyshev type I/II and bessel. High pass, low pass, band pass and band stop variants are available. `examples/iir.cpp` contains examples for iir filter design and using generated coefficients for biquad filtering.

**Comment by chrisdukey** [comment]
Thanks @dlevin256. I was hoping for an example of how it would work with streamed data rather than applying it to a full dataset. I need to apply it to data coming in at 50 samples per second.

**Comment by killdaclick** [comment]
@dlevin256 
@chrisdukey 
Iam also interested how to apply my own biquad coefficients to IIR on the going stream instead of full dataset. Any clue on that?

**Comment by acxz** [comment]
@chrisdukey yeah I can open source it, give me a week tho, this week is kinda hectic for me

**Comment by dlevin256** [comment]
Hi,
You can apply filter (biquad or FIR) to a buffer using `filter<T>`:
https://www.kfrlib.com/newdocs/auto/filter/

`filter.apply` can be used to apply filter to a single buffer of streamed audio. Internal state is kept between calls to `apply` so the output audio is continuous.

```c++
std::unique_ptr<biquad_filter<float>> bqfilter;

void initialize()
{
    // initialize chebyshev2 filter of order 8
    zpk<float> filt                       = iir_lowpass(chebyshev2<float>(8, 80), 0.09);
    // convert to 2nd order sections (suitable for biquad filter) or provide your own coefficients in bqs
    std::vector<biquad_params<float>> bqs = to_sos(filt);
    // create filter object
    bqfilter.reset(new biquad_filter<float>(bqs.data(), bqs.size()));
}

void process_buffer(float* dest, float* source, size_t numSamples)
{
    // this applies filter to source and writes to dest
    bqfilter->apply(dest, source, numSamples);
    // inplace variant: bqfilter->apply(buffer, numSamples)
}
```

**Comment by acxz** [comment]
Thanks for the reply @dlevin256. Will this work for cases when my data stream is not consistent with regards to time? For example I get several samples at 50Hz, but I get a couple at 55 or 60Hz. Does ‘apply’ have an internal timer associated with it?

**Comment by acxz** [comment]
@chrisdukey I haven't forgotten this, just things being boom boom boom at me. I'm reopening this issue though, until we can get @dlevin256 example's working on a datastream.

**Comment by acxz** [comment]
@dlevin256 if you could respond to my concern about handling inconsistently timed samples, that would be much appreciated.

**Comment by dlevin256** [comment]
@acxz 
Currently, filters implemented in KFR only accepts data with stable sample rate.

The main purpose of KFR is to provide building blocks for audio and musical applications/plugins where sample rate are usually known before receiving any data.
For other applications, additional conversion should be implemented before filtering.

Are 50, 55 and 60hz the only sample rates known to be present in the input data stream?
Simple resampler that converts data to 3300hz by inserting zeros between samples (it's standard method to implement poly-phase resamplers) can solve this part of problem. The only difference is that the number of zeros will depend on the input sample rate (3300 / sr - 1). This introduces aliasing after nyquist frequency (that differs for different input sample rates) but good filter applied afterwards should remove it completely. Filter coefficients should be recalculated for sample rate = 3300hz. One drawback is that you'll get 3300hz on the output that however can be downsampled to 50hz. Is this what you want? Or you except variable rate (50/55/60hz to match input)?

numSamples can be 1 but filter performance depends on this number, so if you want the filter to be fast, send maximum available samples to it.
