### ISSUE TITLE
Unexpected resulls with even-numbered highpass filter size

### ISSUE THREAD

**Issue by mujjingun** [kfrlib/kfr#60]
The filter coefficients created by the following code plots the following seemingly low-pass filter:

```cpp
    auto kaiser = to_pointer(kfr::window_kaiser(128, 3.0));

    kfr::univector<dd::fbase, 128> sClutter_coeff;
    kfr::fir_highpass(sClutter_coeff, 0.1, kaiser, true);

    for (auto c : sClutter_coeff) {
        std::cout << c << "\t";
    }
```

![image](https://user-images.githubusercontent.com/6328181/60857308-94fc4480-a1f9-11e9-86dd-6e4cd3d0cd4f.png)

Note that I used the `kfr::fir_highpass` function.

**Comment by dlevin256** [comment]
Highpass FIR filters require odd number of taps.

FIR filters with even number of taps (Type II filters) always have a zero at z=−1 (Nyquist frequency) and can't be used as high pass filters which require 1 at the Nyquist frequency.
