### ISSUE TITLE
kill special_constant::undefined

### ISSUE THREAD

**Issue by bmanga** [kfrlib/kfr#62]
The ```enum class special_constant``` (cometa.hpp:1989) contains an ```undefined``` field.
The function     ```template <typename T> constexpr T special_value::get() const CMT_NOEXCEPT  ``` tries to instantiate and return an unititialized T(cometa.hpp:2025), which is not allowed in a constexpr function. 
Based on a quick grep, ```special_constant::undefined``` does not seem to be used anywhere.
Can it be removed?

EDIT: This regards the dev branch

**Comment by dlevin256** [comment]
Removed in `dev` branch
