### ISSUE TITLE
Unsure how to use the `aweighting()` function

### ISSUE THREAD

**Issue by hendrep** [kfrlib/kfr#64]
Apologies if this is not the right place to place this kind of question.
I am new to kfr.
I am trying to use the aweighting function. I get float pcm data from my audio recorder and then try to use the function like this: 

```
const size_t size = (size_t) 192;
univector<float> buffer = make_univector((float*) audioData, size);
univector<float, size> dB = amp_to_dB(aweighting(buffer));
latestValue= maxof(dB);
```

The values I get after applying the aweighting is very low.
With out aweighting, the max value I cant get is 0dB. With aweighting it is -148.579987
I can't find any information on how to use the function correctly, please point me in the right direction if such information is available. Thank you!

**Comment by dlevin256** [comment]
Hi,

`aweighting` function takes frequency in Hz and outputs the gain that should be applied to the corresponding FFT bin.
