### ISSUE TITLE
error: ‘audio_reader_flac’ was not declared in this scope

### ISSUE THREAD

**Issue by marcoippolito** [kfrlib/kfr#65]
How to read a flac file?

    #include <kfr/base.hpp>
    #include <kfr/dsp.hpp>
    #include <kfr/io.hpp>

    int main() {
 
        audio_reader_flac<float> reader(open_file_for_reading("6319-64726-0013.flac"));
        return 0;
    }

    (kfr) marco@pc:~/kfr$ g++ -std=c++17 flacfileRead.cpp -o flacfileRead
    flacfileRead.cpp: In function ‘int main()’:
    flacfileRead.cpp:7:5: error: ‘audio_reader_flac’ was not declared in this scope
         audio_reader_flac<float> reader(open_file_for_reading("6319-64726-0013.flac"));
         ^~~~~~~~~~~~~~~~~
    flacfileRead.cpp:7:5: note: suggested alternative: ‘__io_read_fn’
         audio_reader_flac<float> reader(open_file_for_reading("6319-64726-0013.flac"));
         ^~~~~~~~~~~~~~~~~
         __io_read_fn
    flacfileRead.cpp:7:23: error: expected primary-expression before ‘float’
          audio_reader_flac<float> reader(open_file_for_reading("6319-64726-0013.flac"));
                            ^~~~~
    (kfr) marco@pc:~/kfr$ 

Looking forward to your kind help.
Marco

**Comment by dlevin256** [comment]
Hi,

`audio_reader_flac` is enabled only if `KFR_ENABLE_FLAC` is defined.

Add this to the command line.
```
-DKFR_ENABLE_FLAC=1
```
Or this at the top of the source.
```c++
#define KFR_ENABLE_FLAC 1
```

Also, you need to add `-lkfr_io` to the command line to link KFR IO library (must be compiled first).

**Comment by marcoippolito** [comment]
Hi Dan,

what am I still doing wrong? 

#define KFR_ENABLE_FLAC 1

#include <kfr/base.hpp>
#include <kfr/dsp.hpp>
#include <kfr/io.hpp>


    int main() {
        audio_reader_flac<float> reader(open_file_for_reading("6319-64726-0013.flac"));
        return 0;
    }


    (kfr) marco@pc:~/kfr$ g++ -std=c++17 -lkfr_io flacfileRead.cpp -o flacfileRead 
    flacfileRead.cpp: In function ‘int main()’:
    flacfileRead.cpp:10:5: error: ‘audio_reader_flac’ was not declared in this scope
         audio_reader_flac<float> reader(open_file_for_reading("6319-64726-0013.flac"));
         ^~~~~~~~~~~~~~~~~
    flacfileRead.cpp:10:5: note: suggested alternative:
    In file included from /usr/include/kfr/io.hpp:27:0,
                     from flacfileRead.cpp:5:
    /usr/include/kfr/io/audiofile.hpp:329:8: note:   ‘kfr::audio_reader_flac’
     struct audio_reader_flac : audio_reader<T>
            ^~~~~~~~~~~~~~~~~
    flacfileRead.cpp:10:23: error: expected primary-expression before ‘float’
         audio_reader_flac<float> reader(open_file_for_reading("6319-64726-0013.flac"));
                           ^~~~~
    (kfr) marco@pc:~/kfr$

**Comment by dlevin256** [comment]
Add `using namespace kfr;` just before the main function.

Or add `kfr::` to `open_file_for_reading` and `open_file_for_reading`

**Comment by marcoippolito** [comment]
(kfr) marco@pc:~/kfr$ g++ -std=c++17 -DKFR_ENABLE_FLAC=1 -lkfr_io flacfileRead.cpp -o 
    flacfileRead
    /usr/bin/ld: cannot find -lkfr_io
    collect2: error: ld returned 1 exit status

**Comment by dlevin256** [comment]
KFR IO library must be compiled before use. Use CMake for this, README.md contains more details.

Alternatively, you can add `include/kfr/io/impl/audiofile-impl.cpp` to the command line instead of `-lkfr_io`.

**Comment by marcoippolito** [comment]
This is what I did for compiling the library: [https://drive.google.com/open?id=1PladNb6sE5EIgGSKXfOjoO9TwKcShFmQ](url) 
Is it correct or do I have to recompile it in a different way?

**Comment by dlevin256** [comment]
This is ok. Just find the directory where `libkfr_io.a` is located and add this directory to the list of link directories (using `-L` GCC flag).

**Comment by marcoippolito** [comment]
(kfr) (base) marco@pc:~/kfr$ g++ -std=c++17 -DKFR_ENABLE_FLAC=1 -L /home/marco/kfr/build
    /libkfr_io.a flacfileRead.cpp -o flacfileRead
        /tmp/ccZvKnrf.o: In function     
        `kfr::audio_reader_flac<float>::audio_reader_flac(std::shared_ptr<kfr::abstract_reader<void> 
        >&&)':
        flacfileRead.cpp:  
           (.text._ZN3kfr17audio_reader_flacIfEC2EOSt10shared_ptrINS_15abstract_readerIvEEE[_ZN3kfr17audio_reader_flacIfEC5EOSt10shared_ptrINS_15abstract_readerIvEEE]+0x88): undefined 
    reference to `drflac_open'
        /tmp/ccZvKnrf.o: In function `kfr::audio_reader_flac<float>::~audio_reader_flac()':
        flacfileRead.cpp:    
    (.text._ZN3kfr17audio_reader_flacIfED2Ev[_ZN3kfr17audio_reader_flacIfED5Ev]+0x26): 
    undefined reference to `drflac_close'
    /tmp/ccZvKnrf.o: In function `kfr::audio_reader_flac<float>::seek(long, kfr::seek_origin)':
    flacfileRead.cpp:    
     (.text._ZN3kfr17audio_reader_flacIfE4seekElNS_11seek_originE[_ZN3kfr17audio_reader_flacIfE4seekElNS_11seek_originE]+0x47): undefined reference to `drflac_seek_to_sample'
    flacfileRead.cpp:    (.text._ZN3kfr17audio_reader_flacIfE4seekElNS_11seek_originE[_ZN3kfr17audio_reader_flacIfE4seekElNS_11seek_originE]+0x65): undefined reference to `drflac_seek_to_sample'
    flacfileRead.cpp:    (.text._ZN3kfr17audio_reader_flacIfE4seekElNS_11seek_originE[_ZN3kfr17audio_reader_flacIfE4seekElNS_11seek_originE]+0x91): undefined reference to `drflac_seek_to_sample'
    /tmp/ccZvKnrf.o: In function `kfr::audio_reader_flac<float>::read(float*, unsigned long)':
    flacfileRead.cpp:(.text._ZN3kfr17audio_reader_flacIfE4readEPfm[_ZN3kfr17audio_reader_flacIfE4readEPfm]+0x77)
    : undefined reference to `drflac_read_s32'
    collect2: error: ld returned 1 exit status
    (kfr) (base) marco@pc:~/kfr$

**Comment by dlevin256** [comment]
Correct command line:
```
g++ -std=c++17  flacfileRead.cpp -DKFR_ENABLE_FLAC=1 -L/home/marco/kfr/build -lkfr_io -I/home/marco/kfr/include -o  flacfileRead
```
`-L` flag specifies full path to library directory, not full path to the library itself. `-l` is still needed in that case.

The order in which source files and libraries appear matters. (sources, then libraries that resolve symbols used before)

Your can read more about this in GCC documentation because this applies to linking process in general, not using a specific library.
