### ISSUE TITLE
gen_sin doesn't work... or I don't know how to use it.

### ISSUE THREAD

**Issue by ccrome** [kfrlib/kfr#66]
Hi there,
   I'm trying out the kfr library and I'm pretty excited by the prospect of using a library like this.  However, with the very first example I tried, gen_sin doesn't seem to work right.

Here's the code:

```
#include "kfr/all.hpp"
#include <math.h>
using namespace std;
using namespace kfr;
using namespace kfr::internal;
int main(int argc, char *argv[])
{
  univector<fbase> x;
  float fs = 16000;
  int samps = 32;
  fbase step = c_pi<fbase>/(samps+1);    //   rad/sample                                                                                                                                                           
  univector<fbase> up = truncate(gen_sin<fbase>(c_pi<fbase>/2, step), samps); // start at pi/2 for cosine.                                                                                                         

  printf("kfr = [");
  for (int i = 0; i < up.size(); i++) {
    printf("%f, ", up[i]);
  }
  printf("]\n");

  printf("sin = [");
  for (int i = 0; i < up.size(); i++) {
    printf("%f, ", sin(c_pi<fbase>/2+i*step));
  }
  printf("]\n");
}
```

When I plot out the results, here's what I get:
![kfr](https://user-images.githubusercontent.com/286973/64463693-cd18ea00-d0b9-11e9-81e6-56ba8000c74f.png)

Any idea what's going on?  I've tried different lengths and arguments, and gen_sin just doesn't seem to work right.

I'm running on a relatively modern intel i7.

Thanks,
 -Caleb

**Comment by dlevin256** [comment]
Hi,

Fixed in `dev` branch.
Thanks for reporting.
