### ISSUE TITLE
How to perform FFT on 1 dimension only when the data is 2D?

### ISSUE THREAD

**Issue by veritas9872** [kfrlib/kfr#67]
Hello. I currently have some 2D real-valued data that I would like to perform the FFT on.
However, I wish to do the FFT on only one dimension, the first.
Is there any way to do this using univector2d? I saw that there was no documentation on this issue.

**Comment by dlevin256** [comment]
How your data is written in memory?

For now, KFR supports only the data continuously written in memory. You can copy data to univector from strided memory before doing FFT and copy it back after FFT.

`univector2d` class provides continuous layout only for the last dimension (in C/C++ notation the last dimension is those that is continuous in memory but that varies in other languages).

**Comment by veritas9872** [comment]
Hello. The input data is a single 1D vector with 2D implemented using the indices of the matrix shape.
The data is from a MATLAB program, so is column-major. Does this mean that the data has to be transposed? That would unfortunately make my program rather inefficient. Also, I need to perform the FFT on the columns.
Currently, I am looking into performing the FFT for each column separately.
