### ISSUE TITLE
make_univector doesn't work with std::vector

### ISSUE THREAD

**Issue by rotkreis** [kfrlib/kfr#68]
Hi there,

I tried to use `make_univector` function to convert input. However, when testing this example taken from the [documentation](https://www.kfrlib.com/newdocs/types/) page
```
std::vector<float> data; // existing data, or std::array<N, float>
float val = rms(make_univector(data)); // No data copy
```

I got these errors:
```
.../kfr-master/include/kfr/io/../base/univector.hpp:478:32: note: candidate function
      template not viable: requires 2 arguments, but 1 was provided
KFR_INTRINSIC univector_ref<T> make_univector(T* data, size_t size)
                               ^
.../kfr-master/include/kfr/io/../base/univector.hpp:485:38: note: candidate function
      template not viable: requires 2 arguments, but 1 was provided
KFR_INTRINSIC univector_ref<const T> make_univector(const T* data, size_t size)
```

It seems that `make_univector` doesn't take `std::vector`, or did I get something wrong? 
Thanks.

**Comment by dlevin256** [comment]
Fixed in the latest version from `dev` branch. Thanks for reporting

**Comment by mipac** [comment]
what about memory alignment in this kind of conversion?

**Comment by dlevin256** [comment]
KFR never assumes that memory is aligned. dynamically allocated `univector` is always cacheline aligned (64 bytes) because of `aligned_allocator`, but this is not the requirement for reference `univector<T, 0>` (created using `make_univector`). Moreover, modern processors read/write aligned memory fast even if instruction assumes unaligned memory. So if your memory was aligned, the memory will be processed fast. But if not, the code will execute ok anyway.

**Comment by mipac** [comment]
thank you for reply
so, how simd is used in kfr functions?
rms used like that exemple can't use simd 
can you give some "good practices" to obtain the best performances?
regards

**Comment by dlevin256** [comment]
SIMD instructions are always used by KFR under the hood. No additional actions needed to enable it.

Memory alignment makes no difference, SIMD will be used here.

**Comment by mipac** [comment]
ok! kind of magic 😅

I've tried to understand reading your code, but lost in the shuffles... 🥴

nice lib, thank you a lot for that good work!
