### ISSUE TITLE
dspplot(ting)

### ISSUE THREAD

**Issue by mipac** [kfrlib/kfr#87]
when I install dspplot module
python setup.py install --prefix=/usr

and kfr

I need to change python_plot.hpp prologue
"import dspplotting as dspplot\n\n"; to "import dspplot as dspplot\n\n"; 

because the module name is dspplot as said in setup.py

Is there an installation procedure that I missed or is it an issue?

thanks

**Comment by dlevin256** [comment]
Currently dspplot is not required to be installed for examples to work.
When example runs dspplot is imported by path.

Or do you want to use dspplot separately from KFR?

**Comment by mipac** [comment]
oh, I thought it was part of the lib
so I try to use it in my code
sorry for the noise

**Comment by dlevin256** [comment]
Not a problem.
It was indeed required in early versions and had to be installed. But in later versions dspplot is imported by path, so kfr examples can find python files without installation. Documentation should mention this.

**Comment by mipac** [comment]
ok
but if I install with setup.py, it seems broken
because of the package name

... but i'm not a python guru as you can see 😄
