### ISSUE TITLE
License ambiguities

### ISSUE THREAD

**Issue by codypiersall** [kfrlib/kfr#91]
This looks like a really cool library!  While I was perusing the sources, I found some license ambiguities:

1. The LICENSE file lists GPL v2 or later, but
2. At least one file, https://github.com/kfrlib/kfr/blob/master/include/kfr/dft/fft.hpp, lists GPLv3 or later.
3. The note at the bottom of the README states `If you want to use KFR in commercial product or a closed-source project, you need to purchase a Commercial License`, which is actually too restrictive for either the GPLv2 or GPLv3 license.  The page it links to is worded better: 

   > If you comply with the GNU Public License v2, you can get KFR for free

    I would recommend wording more similar to this than what is currently on the README.  For example, something like this:

    > If you comply with the GNU Public License v2, you can get KFR for free.  If you would still like to use KFR but cannot comply with the license, e.g. if you are distributing KFR as part of a proprietary application that is closed source, a commercial license [can be purchased](https://www.kfrlib.com/purchase/)

Thanks for the development of this library!

**Comment by samuelriddle** [comment]
The license is GPL v2 or later since KFR 3.0. Some headers were not updated.

**Comment by dlevin256** [comment]
Headers have been updated to reflect license change.
