### ISSUE TITLE
Can this lib modify the source code CPP file and build for cross-platform and IDE ? 

### ISSUE THREAD

**Issue by vippergod123** [kfrlib/kfr#95]
Hey developers,

I have checked out your libs, but I can't see any file CPP. I want to modify C++ file for my business
Does lib work on Android Studio and XCode, Android and iOS projects?

**Comment by samuelriddle** [comment]
This library does work with all IDE you mentioned.
For Xcode, you can generate Xcode library directly from cmake.

For CPP, check out examples folder to see how to use the library.
Check also the README for Usage section.
