### ISSUE TITLE
Is it possible to compute True Peak loudness using kfr's ebu128 ?

### ISSUE THREAD

**Issue by kakyoism** [kfrlib/kfr#98]
As title. The builtin `ebu128` feature set is neat, but it's unclear to me whether it uses True Peak or user has to specify it.

**Comment by samuelriddle** [comment]
You can compute True Peak using Sample Rate Conversion (dsp/sample_rate_conversion.hpp).
Use draft quality and set factor to 4 for sample rates below 96000, 2 for sample rates below 192000. For anything above, Sample Peak = True Peak.

This way is tested and proven to give the correct results matching EBU requirements.
